const CartActionTypes = {
    ADD_ITEM: 'ADD_ITEM',
    ADD_ITEMS: 'ADD_ITEMS',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CLEAR_ALL_ITEM_FROM_CART: 'CLEAR_ALL_ITEM_FROM_CART'
}

export default CartActionTypes;